import mongoose, { type HydratedDocument, type Model, Schema, type Types } from "mongoose";
import type { AbnormalSeverity, AnalysisStatus, PreferredLanguage } from "./constants";
import { ABNORMAL_SEVERITIES, ANALYSIS_STATUSES, PREFERRED_LANGUAGES } from "./constants";
import type { AnalysisTranslationContent } from "../translations/translation.types";
import {
  SUPPORTED_TRANSLATION_LANGUAGES,
  TRANSLATION_STATUSES,
  type TranslationStatus,
} from "../translations/translation.constants";

/** Single structured lab-style finding */
export interface IAbnormalValueItem {
  markerName?: string;
  observedValue?: string;
  unit?: string;
  referenceRange?: string;
  severity: AbnormalSeverity;
}

export interface IAnalysis {
  reportId: Types.ObjectId;
  analysisStatus: AnalysisStatus;
  generatedAt: Date | null;
  summary: string;
  keyFindings: string[];
  possibleConcerns: string[];
  lifestyleSuggestions: string[];
  abnormalValues: IAbnormalValueItem[];
  precautions: string[];
  /** Kept for backward compatibility; mirrors lifestyle suggestions when populated from AI */
  suggestions: string[];
  questionsForDoctor: string[];
  disclaimer: string;
  language: PreferredLanguage;
  translatedContent: Partial<Record<PreferredLanguage, AnalysisTranslationContent>>;
  translatedLanguage: PreferredLanguage | null;
  translationStatus: TranslationStatus;
  /** Optional raw JSON string from the model (truncated in app layer if needed) */
  aiResponseRaw?: string;
  createdAt: Date;
}

export type IAnalysisDocument = HydratedDocument<IAnalysis>;
export type IAnalysisModel = Model<IAnalysis>;

const abnormalValueItemSchema = new Schema<IAbnormalValueItem>(
  {
    markerName: { type: String, trim: true, maxlength: 200 },
    observedValue: { type: String, trim: true, maxlength: 200 },
    unit: { type: String, trim: true, maxlength: 64 },
    referenceRange: { type: String, trim: true, maxlength: 256 },
    severity: {
      type: String,
      enum: {
        values: ABNORMAL_SEVERITIES,
        message: "{VALUE} is not a valid severity",
      },
      default: "unknown",
    },
  },
  { _id: false },
);

const stringList = (maxItems: number, maxItemLen: number) => ({
  type: [String],
  default: [],
  validate: {
    validator: (v: string[]) =>
      Array.isArray(v) &&
      v.length <= maxItems &&
      v.every((s) => typeof s === "string" && s.length <= maxItemLen),
    message: "Invalid string list",
  },
});

const translatedAbnormalValueItemSchema = new Schema(
  {
    markerName: { type: String, trim: true, maxlength: 200 },
    observedValue: { type: String, trim: true, maxlength: 200 },
    unit: { type: String, trim: true, maxlength: 64 },
    referenceRange: { type: String, trim: true, maxlength: 256 },
    severity: {
      type: String,
      trim: true,
      maxlength: 64,
      default: "unknown",
    },
  },
  { _id: false },
);

const translatedContentItemSchema = new Schema(
  {
    summary: {
      type: String,
      required: true,
      trim: true,
      maxlength: 50_000,
      default: "",
    },
    keyFindings: stringList(60, 2000),
    abnormalValues: {
      type: [translatedAbnormalValueItemSchema],
      default: [],
      validate: {
        validator: (v: unknown[]) => Array.isArray(v) && v.length <= 500,
        message: "Too many translated abnormal value entries",
      },
    },
    possibleConcerns: stringList(60, 2000),
    lifestyleSuggestions: stringList(60, 2000),
    precautions: stringList(60, 2000),
    questionsForDoctor: stringList(100, 1000),
    disclaimer: {
      type: String,
      required: true,
      trim: true,
      maxlength: 10_000,
      default: "",
    },
  },
  { _id: false },
);

const analysisSchema = new Schema<IAnalysis, IAnalysisModel>(
  {
    reportId: {
      type: Schema.Types.ObjectId,
      ref: "Report",
      required: [true, "reportId is required"],
      unique: true,
      index: true,
    },
    analysisStatus: {
      type: String,
      enum: {
        values: ANALYSIS_STATUSES,
        message: "{VALUE} is not a valid analysis status",
      },
      default: "pending",
      index: true,
    },
    generatedAt: {
      type: Date,
      default: null,
    },
    summary: {
      type: String,
      required: true,
      trim: true,
      maxlength: 50_000,
      default: "",
    },
    keyFindings: stringList(40, 2000),
    possibleConcerns: stringList(40, 2000),
    lifestyleSuggestions: stringList(40, 2000),
    abnormalValues: {
      type: [abnormalValueItemSchema],
      default: [],
      validate: {
        validator: (v: unknown[]) => Array.isArray(v) && v.length <= 500,
        message: "Too many abnormal value entries",
      },
    },
    precautions: stringList(40, 2000),
    suggestions: stringList(40, 2000),
    questionsForDoctor: stringList(100, 1000),
    disclaimer: {
      type: String,
      required: true,
      trim: true,
      maxlength: 10_000,
      default:
        "This analysis is generated by AI for informational purposes only and is not medical advice. Consult a qualified clinician.",
    },
    language: {
      type: String,
      enum: {
        values: PREFERRED_LANGUAGES,
        message: "{VALUE} is not a supported analysis language",
      },
      required: true,
      default: "en",
    },
    translatedContent: {
      en: {
        type: translatedContentItemSchema,
        default: undefined,
      },
      hi: {
        type: translatedContentItemSchema,
        default: undefined,
      },
    },
    translatedLanguage: {
      type: String,
      enum: {
        values: SUPPORTED_TRANSLATION_LANGUAGES,
        message: "{VALUE} is not a supported translation language",
      },
      default: null,
    },
    translationStatus: {
      type: String,
      enum: {
        values: TRANSLATION_STATUSES,
        message: "{VALUE} is not a valid translation status",
      },
      default: "pending",
      index: true,
    },
    aiResponseRaw: {
      type: String,
      maxlength: 120_000,
      select: false,
    },
    createdAt: {
      type: Date,
      default: () => new Date(),
    },
  },
  {
    versionKey: false,
  },
);

analysisSchema.index({ createdAt: -1 });
analysisSchema.index({ analysisStatus: 1, createdAt: -1 });

export const Analysis = mongoose.model<IAnalysis, IAnalysisModel>("Analysis", analysisSchema);
