import mongoose, { type HydratedDocument, type Model, Schema, type Types } from "mongoose";
import type { AbnormalSeverity, PreferredLanguage } from "./constants";
import { ABNORMAL_SEVERITIES, PREFERRED_LANGUAGES } from "./constants";

/** Single structured lab-style finding */
export interface IAbnormalValueItem {
  markerName?: string;
  observedValue?: string;
  unit?: string;
  referenceRange?: string;
  severity: AbnormalSeverity;
}

export interface IAnalysis {
  reportId: Types.ObjectId;
  summary: string;
  abnormalValues: IAbnormalValueItem[];
  precautions: string[];
  suggestions: string[];
  questionsForDoctor: string[];
  disclaimer: string;
  language: PreferredLanguage;
  createdAt: Date;
}

export type IAnalysisDocument = HydratedDocument<IAnalysis>;
export type IAnalysisModel = Model<IAnalysis>;

const abnormalValueItemSchema = new Schema<IAbnormalValueItem>(
  {
    markerName: { type: String, trim: true, maxlength: 200 },
    observedValue: { type: String, trim: true, maxlength: 200 },
    unit: { type: String, trim: true, maxlength: 64 },
    referenceRange: { type: String, trim: true, maxlength: 256 },
    severity: {
      type: String,
      enum: {
        values: ABNORMAL_SEVERITIES,
        message: "{VALUE} is not a valid severity",
      },
      default: "unknown",
    },
  },
  { _id: false },
);

const analysisSchema = new Schema<IAnalysis, IAnalysisModel>(
  {
    reportId: {
      type: Schema.Types.ObjectId,
      ref: "Report",
      required: [true, "reportId is required"],
      unique: true,
      index: true,
    },
    summary: {
      type: String,
      required: [true, "summary is required"],
      trim: true,
      maxlength: 50_000,
    },
    abnormalValues: {
      type: [abnormalValueItemSchema],
      default: [],
      validate: {
        validator: (v: unknown[]) => Array.isArray(v) && v.length <= 500,
        message: "Too many abnormal value entries",
      },
    },
    precautions: {
      type: [String],
      default: [],
      validate: {
        validator: (v: string[]) =>
          Array.isArray(v) && v.length <= 200 && v.every((s) => typeof s === "string" && s.length <= 2000),
        message: "Invalid precautions array",
      },
    },
    suggestions: {
      type: [String],
      default: [],
      validate: {
        validator: (v: string[]) =>
          Array.isArray(v) && v.length <= 200 && v.every((s) => typeof s === "string" && s.length <= 2000),
        message: "Invalid suggestions array",
      },
    },
    questionsForDoctor: {
      type: [String],
      default: [],
      validate: {
        validator: (v: string[]) =>
          Array.isArray(v) && v.length <= 100 && v.every((s) => typeof s === "string" && s.length <= 1000),
        message: "Invalid questionsForDoctor array",
      },
    },
    disclaimer: {
      type: String,
      required: true,
      trim: true,
      maxlength: 10_000,
      default:
        "This analysis is generated by AI for informational purposes only and is not medical advice. Consult a qualified clinician.",
    },
    language: {
      type: String,
      enum: {
        values: PREFERRED_LANGUAGES,
        message: "{VALUE} is not a supported analysis language",
      },
      required: true,
      default: "en",
    },
    createdAt: {
      type: Date,
      default: () => new Date(),
    },
  },
  {
    versionKey: false,
  },
);

analysisSchema.index({ createdAt: -1 });

export const Analysis = mongoose.model<IAnalysis, IAnalysisModel>("Analysis", analysisSchema);
