import { Types } from "mongoose";
import { analyzeMedicalReportOcrText } from "../ai/openai.service";
import { aiLog } from "../ai/ai.utils";
import { isProduction } from "../config/env";
import { AppError } from "../middleware/errorHandler";
import { Analysis } from "../models/analysis.model";
import type { PreferredLanguage } from "../models/constants";
import { PREFERRED_LANGUAGES } from "../models/constants";
import { Report } from "../models/report.model";

const MIN_OCR_CHARS = 20;

function assertPreferredLanguage(raw: string): PreferredLanguage {
  if ((PREFERRED_LANGUAGES as readonly string[]).includes(raw)) {
    return raw as PreferredLanguage;
  }
  return "en";
}

export interface AnalysisApiPayload {
  summary: string;
  keyFindings: string[];
  abnormalValues: Array<{
    markerName?: string;
    observedValue?: string;
    unit?: string;
    referenceRange?: string;
    severity: string;
  }>;
  possibleConcerns: string[];
  lifestyleSuggestions: string[];
  precautions: string[];
  questionsForDoctor: string[];
  disclaimer: string;
}

export async function runAiAnalysisForReport(
  reportId: string,
  userId: string,
): Promise<{ reportId: string; analysis: AnalysisApiPayload }> {
  if (!Types.ObjectId.isValid(reportId)) {
    throw new AppError("Invalid report id", 400);
  }

  const report = await Report.findOne({
    _id: new Types.ObjectId(reportId),
    userId: new Types.ObjectId(userId),
  }).exec();

  if (!report) {
    throw new AppError("Report not found", 404);
  }

  if (report.ocrStatus !== "completed") {
    throw new AppError("OCR must be completed before AI analysis. Run OCR extract first.", 400);
  }

  const ocrText = report.extractedText?.trim() ?? "";
  if (ocrText.length < MIN_OCR_CHARS) {
    throw new AppError("No OCR text available for this report. Run OCR again or upload a clearer file.", 400);
  }

  const language = assertPreferredLanguage(report.language);

  let analysisDoc = await Analysis.findOne({ reportId: report._id }).exec();

  if (analysisDoc && analysisDoc.analysisStatus === "processing") {
    throw new AppError("AI analysis is already running for this report", 409);
  }

  if (!analysisDoc) {
    analysisDoc = await Analysis.create({
      reportId: report._id,
      analysisStatus: "processing",
      generatedAt: null,
      summary: "Analysis in progress…",
      keyFindings: [],
      possibleConcerns: [],
      lifestyleSuggestions: [],
      abnormalValues: [],
      precautions: [],
      suggestions: [],
      questionsForDoctor: [],
      disclaimer:
        "This analysis is generated by AI for informational purposes only and is not medical advice.",
      language,
    });
    report.analysis = analysisDoc._id;
    await report.save();
  } else {
    analysisDoc.analysisStatus = "processing";
    await analysisDoc.save();
  }

  if (!report.analysis) {
    report.analysis = analysisDoc._id;
    await report.save();
  }

  const docId = analysisDoc._id;

  try {
    const ai = await analyzeMedicalReportOcrText({ ocrText, language });

    const rawJson = JSON.stringify(ai);
    const rawStored =
      rawJson.length > 100_000 ? `${rawJson.slice(0, 100_000)}\n/* truncated */` : rawJson;

    await Analysis.findByIdAndUpdate(docId, {
      analysisStatus: "completed",
      generatedAt: new Date(),
      summary: ai.summary,
      keyFindings: ai.keyFindings,
      possibleConcerns: ai.possibleConcerns,
      lifestyleSuggestions: ai.lifestyleSuggestions,
      abnormalValues: ai.abnormalValues,
      precautions: ai.precautions,
      suggestions: ai.lifestyleSuggestions,
      questionsForDoctor: ai.questionsForDoctor,
      disclaimer: ai.disclaimer,
      language,
      aiResponseRaw: rawStored,
    }).exec();

    const payload: AnalysisApiPayload = {
      summary: ai.summary,
      keyFindings: ai.keyFindings,
      abnormalValues: ai.abnormalValues.map((a) => ({
        markerName: a.markerName,
        observedValue: a.observedValue,
        unit: a.unit,
        referenceRange: a.referenceRange,
        severity: a.severity,
      })),
      possibleConcerns: ai.possibleConcerns,
      lifestyleSuggestions: ai.lifestyleSuggestions,
      precautions: ai.precautions,
      questionsForDoctor: ai.questionsForDoctor,
      disclaimer: ai.disclaimer,
    };

    return { reportId: String(report._id), analysis: payload };
  } catch (err) {
    aiLog("error", "AI analysis failed", {
      reportId,
      message: err instanceof Error ? err.message : String(err),
    });
    await Analysis.findByIdAndUpdate(docId, {
      analysisStatus: "failed",
      generatedAt: new Date(),
      summary:
        (err instanceof AppError ? err.message : "Analysis could not be completed. Please try again later.").slice(
          0,
          5000,
        ),
    }).exec();

    if (err instanceof AppError) {
      throw err;
    }
    const msg = err instanceof Error ? err.message : String(err);
    if (!isProduction) {
      throw new AppError(`AI analysis failed: ${msg}`, 502);
    }
    throw new AppError("AI analysis failed", 502);
  }
}
